#!/usr/bin/env python3.10


# Module imports
# -----------------------------------------------------------------------------


import os
import sys

sys.path.append(os.path.expanduser("~/ytdlp_utils/ytdlp_utils/"))

import channel_checker



# Operations
# -----------------------------------------------------------------------------


if __name__ == "__main__":
    channel_checker.main()
