#!/usr/bin/env python3.10


# Module imports
# -----------------------------------------------------------------------------


import argparse
import os
import sys

sys.path.append(os.path.expanduser("~/ytdlp_utils/ytdlp_utils/"))

from playlist_handler import PlaylistHandler


# Main function
# -----------------------------------------------------------------------------


def main() -> None:
    """Download a Youtube playlist"""

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "playlist_id",
        metavar="PLAYLIST_ID",
        type=str,
        help="URI of the Youtube playlist to download")

    parser.add_argument(
        "-t",
        "--threads",
        type=int,
        default=None,
        help="Number of threads to use for operations")

    args = vars(parser.parse_args())

    ph = PlaylistHandler(
        args.get("playlist_id"),
        max_threads=args.get("threads"))

    ph.run()


# Entrypoint
# -----------------------------------------------------------------------------


if __name__ == "__main__":
    main()
